version: '3.8'

services:

  ## Apache
  www:
    build: ./docker
    container_name: www_todo-list
    ports:
      - '8000:80'
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev

  ## MySql
  db:
    image: mysql:8.0
    container_name: db_todo-list
    volumes:
      - todo-list-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  ## PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_todo-list
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

networks:
  dev:

volumes:
  todo-list-mysql-data: